version: '3'

volumes:
  db2:

services:
  sqlserver:
    image: microsoft/mssql-server-linux
    ports:
    - "1433:1433"
    environment:
    - ACCEPT_EULA=y
    - SA_PASSWORD=Insight!!!Test

  mysql:
    image: mysql/mysql-server:latest
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_ROOT_HOST=%
    - MYSQL_DATABASE=test
 
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=Insight!!!Test
    - POSTGRES_USER=postgres

# docker run --rm -it --name mydb2 --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=Insight!!!Test -e DBNAME=testdb -v ./db2:/database ibmcom/db2
# NOTE: this seems to need the local volume instead of mapping to a disk
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
    - "50000:50000"
    environment:
    - LICENSE=accept
    - DB2INSTANCE=db2inst1
    - DB2INST1_PASSWORD=Insight!!!Test
    - DBNAME=testdb
    - PERSISTENT_HOME=false
    volumes:
    - db2:/database

  # this requires you to log into docker hub and agree to terms of service
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
    - "1521:1521"
    environment:
    - WEB_CONSOLE=false

  sybase:
    image: datagrip/sybase
    ports:
    - "5000:5000"
    environment:
    - SYBASE_USER=test
    - SYBASE_PASSWORD=InsightTest1234
    - SYBASE_DB=test
